I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Character Specific/Pearl/pearl_3.rpy", line 3, in script
    $ userName
  File "game/scripts/Character Specific/Pearl/pearl_3.rpy", line 3, in <module>
    $ userName
NameError: name 'null' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Character Specific/Pearl/pearl_3.rpy", line 3, in script
    $ userName
  File "C:\Users\Rilogator\Documents\Game Dev\RenPy\renpy-7.3.2-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Rilogator\Documents\Game Dev\RenPy\renpy-7.3.2-sdk\renpy\python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scripts/Character Specific/Pearl/pearl_3.rpy", line 3, in <module>
    $ userName
NameError: name 'null' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Gem Blast 3.0.0
Mon Nov 25 08:04:23 2019
